name: Build test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'

      - name: Install dependencies
        run: flutter pub get

      # Build Android APK
      - name: Build APK (Android)
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --release

      # Build macOS app
      - name: Build macOS app
        if: matrix.os == 'macos-latest'
        run: flutter build macos

      # ✅ Build iOS app (only on macOS)
      - name: Build iOS app
        if: matrix.os == 'macos-latest'
        run: flutter build ios --release

      # Build Windows app
      - name: Build Windows app
        if: matrix.os == 'windows-latest'
        run: flutter build windows

      # Upload build artifacts
      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: flutter-build-${{ matrix.os }}
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/macos/Build/Products/Release/*.app
            build/windows/runner/Release/*.exe
            build/ios/iphoneos/Runner.app
