name: Widget Test

on:
  pull_request:
    branches: [ main ]

jobs:
  widget-test:
    name: Run widget test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'
            
      - name: Install dependencies
        run: flutter pub get

      - name: Run tests from specific folder
        run: flutter test test/widgets/**